server:
  address: ":4001"
  name: "Gate4ai Example Server"
  version: "0.1.0"
  log_level: "debug"
  authorization: "users_only" # "users_only", "marked_methods", or "none"

users:
  user1:
    # In YAML, API keys should ideally be stored as their hashes.
    # Hashing "test-key-user1" yields: 002d3590657193543ca073cbf1f43b51963e3478137a73c150782522cae93875
    keys:
      - "002d3590657193543ca073cbf1f43b51963e3478137a73c150782522cae93875" # Hash of "test-key-user1"
    # subscribes: [] # No subscriptions needed for direct access testing

backends: {} # No backends needed for the example server itself 